# Generated by Django 3.2.3 on 2021-05-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepApp', '0003_recordings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
