# Generated by Django 3.2.3 on 2021-05-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepApp', '0004_alter_recordings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='record_choices',
            field=models.CharField(choices=[('zoom', 'zoom'), ('collaborate', 'collaborate')], default='collaborate', max_length=255),
        ),
    ]
