# Generated by Django 3.2.3 on 2021-05-29 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prepApp', '0005_subject_record_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='prepApp.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='day1',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='day2',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
