# Generated by Django 3.2.3 on 2021-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepApp', '0006_auto_20210529_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='record_choices',
            field=models.CharField(max_length=255),
        ),
    ]
